import { graphql } from "./autogenerated";

export const DepositRequestsBySpender = graphql(`
  query fetchDepositRequests($spender: bytea!) {
    deposit_request(where: {spender: {_eq: $spender}}) {
      status
      encoded_asset_addr
      encoded_asset_id
      value
      deposit_addr_h1
      deposit_addr_h2
      nonce
      gas_compensation
      instantiation_tx_hash
      completion_tx_hash
      retrieval_tx_hash
      created_at_total_entity_index
    }
  }
`);

export const DepositRequestStatusById = graphql(`
  query fetchDepositStatus($hash: String!) {
    deposit_request(where: {id: {_eq: $hash}}) {
      status
    }
  }
`);
