version: "3.7"
services:
  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6381 --loglevel debug
    volumes:
      - /redis-data
    ports:
      - "6381:6381"
    expose:
      - 6381

  subtree-updater:
    build:
      context: ../..
      dockerfile: packages/subtree-updater/Mock.Dockerfile
    restart: always
    command: "run subtree-updater --config-name-or-path ${CONFIG_NAME_OR_PATH} --log-dir /logs/subtree-updater --use-mock-prover --fill-batch-latency-ms 3000"
    environment:
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CONFIG_NAME_OR_PATH=${CONFIG_NAME_OR_PATH}
      - SUBGRAPH_URL=${SUBGRAPH_URL}
      - RPC_URL=${RPC_URL}
      - TX_SIGNER_KEY=${TX_SIGNER_KEY}
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../../logs:/logs
      - ../config/configs:/configs

volumes:
  redis-data:
