version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=nocturne
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

    #volumes:
    #  - postgres-data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    depends_on:
      - postgres
    volumes:
      - ./sql:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/nocturne
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=password
      - FLYWAY_SCHEMAS=nocturne
      - NOCTURNE_DB_USER_PASSWORD=password
    entrypoint: []
    command: ["bash", "/flyway/sql/migrate-with-retry.sh"]

  kms:
    # had to use a fork - track this PR to return to main repo https://github.com/nsmithuk/local-kms/pull/38
    #  pinned to a sha to avoid any possible breaking changes
    image: bobanetwork/local-kms@sha256:fb47bc9a2001415ed77a83191d5391c292a4315e98bd138505cc987ec0a232cb
    platform: linux/arm/v7
    ports:
      - "8080:8080"
    environment:
      KMS_ACCOUNT_ID: "123456789012"
      KMS_REGION: "us-east-2"
    volumes:
      - "./local-kms:/init"

#volumes:
#  postgres-data:
