import { CodegenConfig } from "@graphql-codegen/cli";

const SUBGRAPH_URL = "http://localhost:8000/subgraphs/name/nocturne";

const config: CodegenConfig = {
  schema: SUBGRAPH_URL,
  documents: ["src/**/*.ts"],
  ignoreNoDocuments: true, // for better experience with the watcher
  generates: {
    "./src/gql/autogenerated/": {
      preset: "client",
    },
  },
};

export default config;
