import { SUBGRAPH_URL } from "./src/utils";
import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: SUBGRAPH_URL,
  documents: ["src/**/*.ts", "src/**/*.tsx"],
  ignoreNoDocuments: true, // for better experience with the watcher
  generates: {
    "./src/gql/autogenerated/": {
      preset: "client",
    },
  },
};

export default config;
