version: "3.7"
services:
  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6380 --loglevel debug
    volumes:
      - /redis-data
    ports:
      - "6380:6380"
    expose:
      - 6380

  processor:
    build:
      context: ../..
      dockerfile: packages/deposit-screener/Dockerfile
    restart: always
    command: "run processor --config-name-or-path ${CONFIG_NAME_OR_PATH} --log-dir /logs/deposit-screener-processor"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../../logs:/logs
      - ../config/configs:/configs

volumes:
  redis-data:
