import { graphql } from "../autogenerated";

export const LatestIndexedBlock = graphql(`
  query fetchLatestIndexedBlock {
    goerli_goerli_sdk_event_aggregate {
      aggregate {
        max {
          block
        }
      }
    }
  }
`);
