import { graphql } from "../autogenerated";

export const DepositRequestsBySpenderQueryDocument = graphql(`
  query fetchDepositRequests($spender: Bytes!) {
    depositRequests(where: { spender: $spender }) {
      spender
      status
      encodedAssetAddr
      encodedAssetId
      value
      depositAddrH1
      depositAddrH2
      nonce
      gasCompensation
      instantiationTxHash
      completionTxHash
      retrievalTxHash
      createdAtTotalEntityIndex
    }
  }
`);
