import { graphql } from "../autogenerated";

const DepositRequestsBySpenderAndCreatedAtQueryDocument = graphql(`
  query fetchDepositRequestUpdates(
    $spender: Bytes!
    $createdAtIndices: [BigInt!]
  ) {
    depositRequests(
      where: {
        spender: $spender
        createdAtTotalEntityIndex_in: $createdAtIndices
      }
    ) {
      spender
      status
      encodedAssetAddr
      encodedAssetId
      value
      depositAddrH1
      depositAddrH2
      nonce
      gasCompensation
      instantiationTxHash
      completionTxHash
      retrievalTxHash
      createdAtTotalEntityIndex
    }
  }
`);

export default DepositRequestsBySpenderAndCreatedAtQueryDocument;
