import { CodegenConfig } from "@graphql-codegen/cli";
import dotenv from "dotenv";

dotenv.config();

if (!process.env.HASURA_GRAPHQL_ADMIN_SECRET) {
  throw new Error("HASURA_GRAPHQL_ADMIN_SECRET is not set");
}

const config: CodegenConfig = {
  schema: {
    "https://immune-bunny-99.hasura.app/v1/graphql": {
      headers: {
        "content-type": "application/json",
        "x-hasura-admin-secret": process.env.HASURA_GRAPHQL_ADMIN_SECRET
      }
    },
  },
  documents: ["src/gql/queries.ts"],
  ignoreNoDocuments: true, // for better experience with the watcher
  generates: {
    "./src/gql/autogenerated/": {
      preset: "client",
    },
  },
};

export default config;
