name: Build and Test Packages
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "v18.12.1"
      - name: Enable Corepack
        run: corepack enable
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Rapidsnark dependencies
        run: sudo apt-get install -y build-essential libgmp-dev libsodium-dev nasm nlohmann-json3-dev
      - name: Yarn install
        run: |
          yarn install --immutable
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          if: steps.restore-node-modules.outputs.cache-hit != 'true'
      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - name: Yarn lint
        run: |
          yarn lint
      - name: Yarn prettier
        run: |
          yarn prettier:check
      - name: Yarn build
        run: |
          yarn build
      - name: Yarn test:unit
        run: |
          yarn test:unit
      - name: Yarn test:ci
        run: |
          yarn test:ci
