name: unit test
on: [push]
jobs:
  build-and-test:
    runs-on: going-merry
    steps:
      - uses: actions/checkout@v3
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: install foundryup
        run: curl -L https://foundry.paradigm.xyz | bash && echo "$PATH:/home/runner/.foundry/bin" >> $GITHUB_PATH
      - name: yarn install
        run: |
          yarn install --immutable
      - name: yarn lint
        run: |
          yarn lint
      - name: yarn prettier
        run: |
          yarn prettier:check
      - name: yarn build
        run: |
          yarn build
      - name: yarn test:unit
        run: |
          yarn test:unit
      - name: yarn test:ci
        run: |
          yarn test:ci
