name: e2e test
on: [ push ]
jobs:
  build-and-test-e2e:
    runs-on: going-merry
    steps:
      - name: checkout repo and get submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: install foundryup
        run: curl -L https://foundry.paradigm.xyz | bash && echo "$PATH:/home/runner/.foundry/bin" >> $GITHUB_PATH
      - name: install foundry
        run: foundryup
      - name: yarn install
        run: |
          yarn install --immutable
      - name: yarn build
        run: |
          yarn build
      - name: yarn test:e2e
        run: |
          yarn test:e2e

