name: Build and Test Packages
on: [push]
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "v18.12.1"
          cache: "yarn"
      - name: enable Corepack
        run: corepack enable
      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-f3c20d5664c8773d4ec3b2b67148cc1032f48f58
      - name: install Rapidsnark dependencies
        run: sudo apt-get install -y build-essential libgmp-dev libsodium-dev nasm nlohmann-json3-dev
      - name: yarn install
        run: |
          yarn install --immutable
      - name: Yarn lint
        run: |
          yarn lint
      - name: yarn prettier
        run: |
          yarn prettier:check
      - name: yarn build
        run: |
          yarn build
      - name: yarn test:unit
        run: |
          yarn test:unit
      - name: yarn test:ci
        run: |
          yarn test:ci
