name: Build/Cache Docker + E2E Tests
on: [ push ]
jobs:
  build-and-test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo and get submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "v18.12.1"
          cache: "yarn"
      - name: Enable Corepack
        run: corepack enable
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Foundryup 
        run: foundryup
      - name: Yarn install
        run: |
          yarn install --immutable
      - name: Yarn build
        run: |
          yarn build
      - name: Yarn test:e2e
        run: |
          yarn test:e2e
